import type { ExceptionItem, ReconciliationProfile } from "./types";

export function ExceptionsView({ profile, items, search, setSearch, severity, setSeverity, resolved, select }: { profile?: ReconciliationProfile; items: ExceptionItem[]; search: string; setSearch: (value: string) => void; severity: string; setSeverity: (value: string) => void; resolved: string[]; select: (item: ExceptionItem) => void }) {
  const critical = items.filter(item => item.severity === "Critical" && item.status !== "Resolved").length;
  return <div className="ops-content page-flow focused-exceptions">
    <section className="essential-metrics compact"><article><p>Open exceptions</p><h2>{profile?.openExceptions.toLocaleString() ?? "0"}</h2></article><article><p>Critical items</p><h2>{critical}</h2></article><article><p>Unresolved value</p><h2>{profile?.unresolvedValue ?? "$0"}</h2></article></section>
    <section className="exception-card simple-exception-card"><div className="table-toolbar"><div><p>Review queue</p><h3>Exceptions</h3></div><div className="toolbar-actions"><label className="ops-search">⌕<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search exceptions" /></label><select aria-label="Filter by severity" value={severity} onChange={event => setSeverity(event.target.value)}><option>All severity</option><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></div></div>{items.length ? <div className="simple-exception-list"><div className="simple-exception-head"><span>Issue</span><span>Amount</span><span>Age</span><span>Owner</span><span>Status</span></div>{items.map(item => <button className="simple-exception-row" onClick={() => select(item)} key={item.id}><div><strong>{item.type}</strong><small>{item.id} · {item.source}</small></div><b>{item.amount}</b><span>{item.age}</span><span>{item.owner}</span><span><i className={`severity-pill ${item.severity.toLowerCase()}`}>{item.severity}</i><i className={`state-pill ${resolved.includes(item.id) ? "resolved" : item.status.toLowerCase()}`}>{resolved.includes(item.id) ? "Resolved" : item.status}</i><b>›</b></span></button>)}</div> : <div className="empty-workspace"><span>✓</span><h3>No exceptions found</h3><p>Try a different search or severity.</p></div>}</section>
  </div>;
}
