import { useRef } from "react";
import type { DataSource, ImportBatch, IngestFileInput } from "./types";

export function ImportsView({ imports, sources, onIngest, onValidate, onNormalize, busy }: { imports: ImportBatch[]; sources: DataSource[]; onIngest: (input: Omit<IngestFileInput, "profileId">) => void; onValidate: (id: string) => void; onNormalize: (id: string) => void; busy: string }) {
  const fileRef = useRef<HTMLInputElement>(null);
  const upload = (file?: File) => onIngest({ fileName: file?.name ?? "processor_transactions_20260824.csv", sourceId: sources[0]?.id ?? "SRC-VISA", size: file?.size ?? 18520000 });
  return <div className="ops-content page-flow">
    <section className="ingest-hero"><div><span className="stage-icon blue-stage">↓</span><div><p>INBOUND CONTROL</p><h2>Bring payment data into one controlled pipeline</h2><small>CSV and Excel work now. The backend contract also defines SFTP, API, webhook, and database source boundaries.</small></div></div><div className="ingest-actions"><input ref={fileRef} type="file" accept=".csv,.xlsx,.xls" onChange={event => upload(event.target.files?.[0])} hidden /><button className="secondary-action" onClick={() => fileRef.current?.click()}>Choose file</button><button className="primary-action" onClick={() => upload()} disabled={Boolean(busy)}>＋ Upload mock CSV</button></div></section>
    <section className="ingest-channels">{[{ icon: "▤", title: "CSV / Excel", detail: "Manual upload with schema, count and duplicate controls", state: "Available" }, { icon: "⇣", title: "Managed SFTP", detail: "Scheduled pulls with checksum and late-file monitoring", state: "Contract ready" }, { icon: "⌁", title: "API / Webhook", detail: "Streaming processor events and settlement callbacks", state: "Contract ready" }, { icon: "▦", title: "Ledger / Database", detail: "Controlled extracts from internal accounting records", state: "Contract ready" }].map(channel => <article key={channel.title}><span>{channel.icon}</span><div><h3>{channel.title}</h3><p>{channel.detail}</p></div><i>{channel.state}</i></article>)}</section>
    <section className="imports-card"><div className="table-toolbar"><div><p>File control history</p><h3>Import batches</h3></div><div className="backend-chip"><i />Mock repository · backend functions active</div></div>{imports.length ? <div className="imports-table"><div className="imports-head"><span>Batch & source</span><span>Records</span><span>Valid</span><span>Duplicates</span><span>Control result</span><span>Action</span></div>{imports.map(batch => <article className="imports-row" key={batch.id}><div><strong>{batch.fileName}</strong><small>{batch.id} · {batch.sourceName} · {batch.receivedAt}</small></div><span>{batch.records.toLocaleString()}</span><span>{batch.validRecords.toLocaleString()}</span><span>{batch.duplicates.toLocaleString()}</span><div><i className={`run-status ${batch.status === "Failed" ? "review" : batch.status === "Normalized" ? "complete" : "running"}`}>{batch.status}</i>{batch.issues[0] && <small>{batch.issues[0]}</small>}</div><button onClick={() => batch.status === "Validating" ? onValidate(batch.id) : onNormalize(batch.id)} disabled={batch.status === "Failed" || batch.status === "Normalized"}>{batch.status === "Validating" ? "Validate" : batch.status === "Validated" ? "Normalize" : "Done"}</button></article>)}</div> : <div className="empty-workspace"><span>↓</span><h3>No imports for this profile</h3><p>Upload a mock CSV or connect a source to begin the controlled pipeline.</p></div>}</section>
  </div>;
}
