import type { CanonicalTransaction, ImportBatch, SourceMapping } from "./types";

export function NormalizationView({ mappings, transactions, imports, onNormalize }: { mappings: SourceMapping[]; transactions: CanonicalTransaction[]; imports: ImportBatch[]; onNormalize: (id: string) => void }) {
  const pending = imports.find(item => item.status === "Validated");
  const coverage = mappings.length ? Math.round(mappings.reduce((total, mapping) => total + mapping.coverage, 0) / mappings.length) : 0;
  const duplicates = imports.reduce((total, batch) => total + batch.duplicates, 0);
  return <div className="ops-content page-flow">
    <section className="canonical-banner"><div><p>CANONICAL TRANSACTION MODEL</p><h2>One format across processors, schemes, ledgers, banks, and wallets</h2><small>Original source records remain untouched; normalized fields and every transform are versioned for reproducibility.</small></div>{pending ? <button className="primary-action" onClick={() => onNormalize(pending.id)}>Normalize {pending.id}</button> : <span className="control-ok">✓ All validated batches normalized</span>}</section>
    <section className="schema-strip">{["source", "externalTransactionId", "internalTransactionId", "amount", "currency", "fee", "status", "transactionTime", "settlementTime", "account", "metadata"].map(field => <code key={field}>{field}</code>)}</section>
    <section className="normalization-grid"><div className="mapping-list"><div className="table-toolbar"><div><p>Source configuration</p><h3>Field mappings</h3></div><button className="secondary-action">＋ New mapping</button></div>{mappings.length ? mappings.map(mapping => <article key={mapping.sourceId}><header><div><strong>{mapping.sourceName}</strong><small>{mapping.lastUpdated}</small></div><b>{mapping.coverage}% mapped</b></header>{mapping.mappings.map(item => <div className="mapping-row" key={item.sourceField}><code>{item.sourceField}</code><span>→</span><strong>{item.canonicalField}</strong><small>{item.transform ?? "Direct"}</small></div>)}</article>) : <div className="empty-workspace"><span>↔</span><h3>No field mappings configured</h3><p>Create a mapping after the first source file is available.</p></div>}</div><aside className="data-quality"><p>Normalization controls</p><h3>Profile quality gate</h3><dl><div><dt>Mappings configured</dt><dd>{mappings.length}</dd></div><div><dt>Average field coverage</dt><dd>{coverage}%</dd></div><div><dt>Canonical samples</dt><dd>{transactions.length}</dd></div><div><dt>Duplicate IDs quarantined</dt><dd>{duplicates}</dd></div></dl><div className="quality-score"><span>{coverage}%</span><small>Mapping coverage</small></div></aside></section>
    <section className="canonical-table"><div className="table-toolbar"><div><p>Normalized output</p><h3>Canonical records sample</h3></div><button className="secondary-action">Inspect metadata</button></div>{transactions.length ? <><div className="canonical-head"><span>Transaction ID</span><span>Source reference</span><span>Amount</span><span>Fee</span><span>Status</span><span>Settlement time</span></div>{transactions.map(transaction => <article key={transaction.id}><div><strong>{transaction.id}</strong><small>{transaction.source} · {transaction.account}</small></div><code>{transaction.externalTransactionId}</code><b>{transaction.currency} {transaction.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</b><span>{transaction.currency} {transaction.fee.toFixed(2)}</span><i className="state-pill resolved">{transaction.status}</i><span>{transaction.settlementTime}</span></article>)}</> : <div className="empty-workspace"><span>◇</span><h3>No canonical records yet</h3><p>Validated and normalized imports will appear here as a controlled sample.</p></div>}</section>
  </div>;
}
