import { useMemo, useState } from "react";
import { ProfileStatus } from "./PortfolioView";
import type { ReconciliationProfile } from "./types";

export function ProfilesView({ profiles, selectedProfileId, openProfile, createProfile }: { profiles: ReconciliationProfile[]; selectedProfileId: string; openProfile: (id: string) => void; createProfile: () => void }) {
  const [search, setSearch] = useState("");
  const visible = useMemo(() => profiles.filter(profile => `${profile.name} ${profile.description} ${profile.owner} ${profile.currency}`.toLowerCase().includes(search.toLowerCase())), [profiles, search]);
  return <div className="ops-content page-flow"><section className="profiles-intro"><div><span className="stage-icon blue-stage">▦</span><div><p>CONFIGURATION WORKSPACES</p><h2>Profiles keep reconciliation logic and operations separate</h2><small>Connections may be shared, while mappings, rules, runs, exceptions, and reporting stay profile-specific.</small></div></div><button className="primary-action" onClick={createProfile}>＋ Create profile</button></section><section className="profiles-card"><div className="table-toolbar"><div><p>Profile directory</p><h3>{profiles.length} reconciliation profiles</h3></div><div className="toolbar-actions"><label className="ops-search">⌕<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search profiles" /></label><button className="secondary-action">Status: All</button></div></div><div className="profiles-grid">{visible.map(profile => <article className={profile.id === selectedProfileId ? "selected" : ""} key={profile.id}><header><span className="profile-avatar">{profile.name.split(" ").map(word => word[0]).join("").slice(0, 2)}</span><ProfileStatus status={profile.status} /></header><h3>{profile.name}</h3><p>{profile.description}</p><div className="profile-meta"><span>{profile.currency}</span><span>{profile.timezone.replace("America/", "")}</span><span>{profile.sourceIds.length} sources</span></div><dl><div><dt>Match rate</dt><dd>{profile.matchRate}</dd></div><div><dt>Open exceptions</dt><dd>{profile.openExceptions.toLocaleString()}</dd></div><div><dt>Last run</dt><dd>{profile.lastRun}</dd></div><div><dt>Next run</dt><dd>{profile.nextRun}</dd></div></dl><footer><span>Owner · <strong>{profile.owner}</strong></span><button onClick={() => openProfile(profile.id)}>{profile.id === selectedProfileId ? "Open current profile" : "Open profile"} →</button></footer></article>)}</div></section></div>;
}
